# Generated by Django 3.2.25 on 2024-06-10 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20240610_1528'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailverification',
            options={'verbose_name': 'Верификация почты', 'verbose_name_plural': 'Верификация почты'},
        ),
    ]
