# Generated by Django 3.2.25 on 2024-06-11 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_emailverification_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailverification',
            options={'verbose_name': 'Верификация почты', 'verbose_name_plural': 'Верификаций почты'},
        ),
    ]
